Scriptname MTF_Plugin_Combat extends MTF_Plugin_Base
{Combat module — combat triggers + martial offense. Thin subclass of
 MTF_Plugin_Base: all condition/effect dispatch is id-keyed and inherited
 unchanged; only the plugin identity differs. Catalog: mtf.combat.json
 (generated by tools/build_base_catalog.py). Part of the v0.3.9 mtf.base split.}

string Function GetPluginId()
    return "mtf.combat"
EndFunction
