#!/usr/bin/env python3
"""One-shot migrator: collapse `param`/`param2`/`extras[]` → uniform `paramN`.

Scope:
  1. Plugin catalog files (6 non-Base catalogs — Base is regenerated by
     `build_base_catalog.py`):
        - rename `.effects[i].param` → `.effects[i].param1`
        - rename `.effects[i].extras[k]` → `.effects[i].param{3+k}` (strip `name`)
        - bump `schemaversion` to 2
  2. Test preset JSON files:
        - in every `.slot[s].effect[e]`:
            • rename `param` → `param1`
            • for any `ex` block (object of named values), look up the owning
              effect's extras order from the live catalog and rewrite to
              `param{3+k}` keys
        - bump `schemaversion` 7 → 8

Idempotent: re-running is safe (already-migrated entries are skipped).

Run: python tools/migrate_paramN.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAT_DIR = ROOT / "data" / "SKSE" / "Plugins" / "StorageUtilData" / \
    "MagicTattoosFramework" / "plugins"
PRESET_DIR = ROOT / "test-pack" / "SKSE" / "Plugins" / "StorageUtilData" / \
    "MagicTattoosFramework" / "presets"


def migrate_catalog(path: Path) -> bool:
    """Returns True if file was rewritten."""
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schemaversion") == 2:
        return False  # already migrated

    for eff in data.get("effects", []):
        # param → param1
        if "param" in eff and "param1" not in eff:
            eff["param1"] = eff.pop("param")
        # extras[k] → param{3+k}, stripping the `name` field
        if "extras" in eff:
            for k, ex in enumerate(eff["extras"]):
                n = k + 3
                if n > 5:
                    raise ValueError(f"{path.name} effect {eff.get('id')} has > 3 extras")
                pN = {kk: vv for kk, vv in ex.items() if kk != "name"}
                eff[f"param{n}"] = pN
            del eff["extras"]

    # Always bump schema, even when there's no content delta (catalogs with
    # zero `param`/`extras` shapes still need to advertise the new schema so
    # consumers don't get tripped up by version checks).
    data["schemaversion"] = 2
    path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return True


def load_extras_order(catalogs: dict) -> dict:
    """Build (pluginId, effectId) → list[extraName] map from the PRE-migration
    catalog snapshots. Used to map preset `ex.<name>` values to the right
    paramN slot when the catalog uses positional schema.

    We snapshot BEFORE migrating catalogs so we still have access to the
    `name` fields that get stripped in the new schema.
    """
    extras_map: dict = {}
    for cat in catalogs.values():
        pid = cat.get("pluginid", "")
        for eff in cat.get("effects", []):
            eid = eff.get("id", "")
            names = []
            for ex in eff.get("extras", []) or []:
                names.append(ex.get("name", ""))
            extras_map[(pid, eid)] = names
    return extras_map


def migrate_preset(path: Path, extras_map: dict) -> bool:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schemaversion", 7) >= 8:
        return False

    changed = False
    for slot in data.get("slot", []):
        effs = slot.get("effect", [])
        for eff in effs:
            # `param` → `param1`
            if "param" in eff and "param1" not in eff:
                eff["param1"] = eff.pop("param")
                changed = True
            # `ex` block (named) → paramN positional. Need to know the
            # effect's extras order, which we look up from the pre-migration
            # catalog snapshot by parsing the key "<pluginid>:<effectId>".
            if "ex" in eff:
                key = eff.get("key", "")
                if ":" in key:
                    pid, eid = key.split(":", 1)
                    names = extras_map.get((pid, eid), [])
                    for k, name in enumerate(names):
                        n = k + 3
                        if name in eff["ex"]:
                            eff[f"param{n}"] = eff["ex"][name]
                del eff["ex"]
                changed = True

    if changed:
        data["schemaversion"] = 8
        # Match the existing tab indentation of test presets.
        path.write_text(
            json.dumps(data, indent="\t", ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        return True
    return False


def main():
    # 1. Snapshot ALL catalogs BEFORE migration so we keep the `extras[].name`
    # field around for preset mapping.
    catalogs = {}
    for cf in sorted(CAT_DIR.glob("*.json")):
        catalogs[cf.name] = json.loads(cf.read_text(encoding="utf-8"))
    extras_map = load_extras_order(catalogs)

    # 2. Migrate catalogs.
    print("== Catalogs ==")
    for cf in sorted(CAT_DIR.glob("*.json")):
        if migrate_catalog(cf):
            print(f"  migrated {cf.name}")
        else:
            print(f"  (skip)   {cf.name}")

    # 3. Migrate test presets.
    print("== Test presets ==")
    if not PRESET_DIR.exists():
        print(f"  no preset dir at {PRESET_DIR}")
        return
    for pf in sorted(PRESET_DIR.glob("*.json")):
        if migrate_preset(pf, extras_map):
            print(f"  migrated {pf.name}")
        else:
            print(f"  (skip)   {pf.name}")


if __name__ == "__main__":
    main()
